# Site settings
baseurl: ""
google_analytics: "'UA-45998043-1'"
use_analytics: true

# Build settings

sass:
  sass_dir: _sass
exclude: ["README.md", "Rakefile", "changelog.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env"]

collections:
  institutions:
    output: false
